---
title: "AffordableHousingThomasD"
output: html_notebook
---

```{r}
install.packages("geosphere")
```



```{r}
library(tidyverse)
library(sf)
library(geosphere)

filtered_sales <- read_csv("../data/filtered_sales.csv")
LIHTC <- read_csv("../data/LIHTC.csv")
barnes <- read_csv("../data/barnes.csv")
property_details <- read_csv("../data/property_details.csv")
```

```{r}
property_details <- property_details |> 
  mutate(
    longitude = as.numeric(str_extract(centroid, "\\((.+),", group = 1)),
    latitude = as.numeric(str_extract(centroid, ",(.+)\\)", group = 1))
    )


```

```{r}
ParkRichRoadLIHTC <- LIHTC |> 
  filter(HUD_ID == 'TNA20130015')

ParkRichRoadLIHTC
```

```{r}
sales_total <- inner_join(property_details, filtered_sales, by = 'apn') |> 
  mutate(
    longitude = as.numeric(longitude),
    latitude = as.numeric(latitude)
    )
sales_total
```



```{r}
distance_func <- function(row) {
  longitude <- as.numeric(row[["longitude"]])  
  latitude <- as.numeric(row[["latitude"]])    
  
  distVincentySphere(c(longitude, latitude), c(ParkRichRoadLIHTC[['LONGITUDE']], ParkRichRoadLIHTC[['LATITUDE']]))
}
```



```{r}
summary(sales_total$longitude)
summary(sales_total$latitude)
```


```{r}
distance_value <- distVincentySphere(c(-110.32,40.5524),c(-112.3638,36.266))
distance_value
```

```{r}

sales_total <- sales_total |> 
  drop_na(latitude) |> 
  drop_na(longitude)

sales_total


```

st_distance



```{r}
sales_total <- sales_total |> 
  mutate(distance_to_ParkRich = apply(sales_total,1,distance_func))

sales_total <- sales_total |> 
  mutate(less2000ft = distance_to_ParkRich <= (2000 * .3048)) |> 
  mutate(btwn2and3thoft = (distance_to_ParkRich >= (2000 * .3048)) & (distance_to_ParkRich <= (3000 * .3048)))

sales_total <- sales_total |> 
  mutate(distance_to_ParkRichFeet = distance_to_ParkRich * 3.2808)

sales_total |> 
  filter(btwn2and3thoft)
```

```{r}
sales_total <- sales_total |> 
  mutate(ownedyear = year(ownerdate))


sales_total <- sales_total |> 
  mutate(years_from_PR = ownedyear - ParkRichRoadLIHTC[['YR_ALLOC']])


sales_total <- sales_total |> 
  mutate(fiveyearsbefore = years_from_PR <= -1 & years_from_PR >= -5) |> 
  mutate(fiveyearsafter = years_from_PR >= 1 & years_from_PR <= 5)



sales_total <- sales_total |>   
  mutate(group = case_when(less2000ft ~ "treatment",
        btwn2and3thoft ~ "control"))

sales_total <- sales_total |>   
  mutate(befOrAfter = case_when(fiveyearsbefore ~ "pre",
        fiveyearsafter ~ "post"))


sales_total |> 
  filter()
```

```{r}

sales_total_edited <- sales_total |> 
  filter((less2000ft | btwn2and3thoft) & (fiveyearsbefore | fiveyearsafter))

sales_total_edited

sales_total |> 
  filter(less2000ft | btwn2and3thoft)

sales_total_edited |> 
  summary(distance_to_ParkRich)
```





```{r}
diff_of_diff <- sales_total_edited |> 
  
  group_by(group, befOrAfter) |> 
  summarize(average = mean(amount))

diff_of_diff
```


```{r}
(diff_of_diff$average[[3]] - diff_of_diff$average[[4]]) - (diff_of_diff$average[[1]] - diff_of_diff$average[[2]])
```



```{r}
sales_total_edited
```


```{r}
sales_total_edited_allyears <- sales_total |> 
  filter((less2000ft | btwn2and3thoft))

```



```{r}
lm(amount ~ group * years_from_PR, data = sales_total_edited) |> 
  summary()
```

```{r}
lm(amount ~ group * years_from_PR, data = sales_total_edited_allyears) |> 
  summary()
```



```{r}
diff_of_diff <- function(ID) {
  
  ID_Location <- LIHTC |> 
  filter(HUD_ID == ID)
  print("1")
  
  internal_distance_func <- function(row) {
  longitude <- as.numeric(row[["longitude"]])  
  latitude <- as.numeric(row[["latitude"]])    
  distVincentySphere(c(longitude, latitude), c(ID_Location[['LONGITUDE']], ID_Location[['LATITUDE']]))
  }
  print("2")
  
  internal_sales_total <- inner_join(property_details, filtered_sales, by = 'apn') |> 
  mutate(
    longitude = as.numeric(longitude),
    latitude = as.numeric(latitude)
    )
  
  print("4")
  internal_sales_total <- internal_sales_total |> 
  mutate(distance_to_ParkRich = apply(internal_sales_total,1,internal_distance_func))
  print("5")
  internal_sales_total <- internal_sales_total |> 
  mutate(less2000ft = distance_to_ParkRich <= (2000 * .3048)) |> 
  mutate(btwn2and3thoft = (distance_to_ParkRich >= (2000 * .3048)) & (distance_to_ParkRich <= (3000 * .3048)))
  print("6")
  internal_sales_total <- internal_sales_total |> 
  mutate(distance_to_ParkRichFeet = distance_to_ParkRich * 3.2808)
  print("7")
  internal_sales_total <- internal_sales_total |> 
  mutate(ownedyear = year(ownerdate))
  print("8")

  internal_sales_total <- internal_sales_total |> 
  mutate(years_from_PR = ownedyear - ID_Location[['YR_ALLOC']])
  print("9")

  internal_sales_total <- internal_sales_total |> 
  mutate(fiveyearsbefore = years_from_PR <= -1 & years_from_PR >= -5) |> 
  mutate(fiveyearsafter = years_from_PR >= 1 & years_from_PR <= 5)
  print("10")


  internal_sales_total <- internal_sales_total |>   
  mutate(group = case_when(less2000ft ~ "treatment",
        btwn2and3thoft ~ "control"))
  print("11")
  internal_sales_total <- internal_sales_total |>   
  mutate(befOrAfter = case_when(fiveyearsbefore ~ "pre",
        fiveyearsafter ~ "post"))
  
  print("12")  
  
  internal_sales_total_edited <- internal_sales_total |> 
  filter((less2000ft | btwn2and3thoft) & (fiveyearsbefore | fiveyearsafter))
  
  print('13')
  
  internal_diff_of_diff <- internal_sales_total_edited |> 
  
    group_by(group, befOrAfter) |> 
    summarize(average = mean(amount))

  
  internal_sales_total_edited <- internal_sales_total_edited |> 
    mutate(AffordableHousingName = ID_Location[['PROJECT']])
  
  internal_sales_total_edited
  
  
#  (internal_diff_of_diff$average[[3]] - internal_diff_of_diff$average[[4]]) - (internal_diff_of_diff$average[[1]] - internal_diff_of_diff$average[[2]])
  
}
```

do.call


n = length(LIHTC_properties)
datalist = vector("list", length = n)
for (i in 1:50) {
  unit <- get_affordable_housing_df(LIHTC_properties[i], drop_outside_years = TRUE)
  datalist[[i]] <- unit
}

LIHTC_all_properties_data = do.call(rbind, datalist)

```{r}
value <- diff_of_diff('TNA20110543')
```


```{r}
LIHTC_properties <- as.vector(LIHTC$HUD_ID)
LIHTC_properties
n = length(LIHTC_properties)
datalist = vector("list", length = n)
for (i in 1:10) {
  unit <- diff_of_diff(LIHTC_properties[i])
  datalist[[i]] <- unit
}

LIHTC_all_properties_data = do.call(rbind, datalist)
```

```{r}
LIHTC_all_properties_data
```

